/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rh_example_NativeBridge */

#ifndef _Included_com_rh_example_NativeBridge
#define _Included_com_rh_example_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rh_example_NativeBridge
 * Method:    helloNative
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_com_rh_example_NativeBridge_helloNative
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
